# Generated by Django 6.0.5 on 2026-06-03 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kabkota',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('province', models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, related_name='kabkota_set', to='beranda.provinsi')),
            ],
            options={
                'db_table': 'regencies',
            },
        ),
    ]
