# Generated by Django 6.0.5 on 2026-06-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0002_kabkota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('regency', models.ForeignKey(db_column='regency_id', on_delete=django.db.models.deletion.CASCADE, related_name='kecamatan_set', to='beranda.kabkota')),
            ],
            options={
                'db_table': 'districts',
            },
        ),
    ]
