# Generated by Django 6.0.5 on 2026-06-12 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beranda', '0003_kecamatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('alt_name', models.CharField(blank=True, default='', max_length=255)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('district', models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.CASCADE, related_name='kelurahan_set', to='beranda.kecamatan')),
            ],
            options={
                'db_table': 'villages',
            },
        ),
    ]
